[package]
name = "pcapng"
version = "0.0.1"
authors = ["Richo Healey <richo@psych0tik.net>"]

repository = "https://github.com/richo/pcapng-rs"
description = "a pcapng parser, implemented in rust"
license = "MIT"

[dependencies]
nom = "*"
